<?php

/**

 * Created by PhpStorm.

 * User: Administrator

 * Date: 2018/1/26 0026

 * Time: 下午 1:59

 */



namespace frontend\controllers;

use common\helpers\ArrayHelper;

use common\helpers\Convert;
use common\models\Attr;

use common\models\AttrImages;

use common\models\AttrImagesSelect;

use common\models\AttrValue;

use common\models\Category;

use common\models\CategoryImages;
use common\models\Images;

use common\models\SitemapProduct;
use Faker\Provider\Image;

use League\Glide\Http\NotFoundException;

use Yii;

use yii\helpers\Html;

use common\models\UrlAd;







class ProductController extends CommonController

{
   

    public function init()

    {


        parent::init(); // TODO: Change the autogenerated stub

    }



    public function actionIndex(){



    }

    public function actionDetail(){
        parent::common();

        if(!empty(Yii::$app->request->get('id'))){

            $id=Yii::$app->request->get('id');
            $convert=new Convert(32);
            $id=$convert->stringToId($id);
//            echo $id;
//            exit();
            $item=Images::find()

                ->where(['id'=>$id])


                ->one();

            if (!isset($item)){

                throw new \yii\web\NotFoundHttpException('The requested page does not exist.');

            }

            $item->click=$item->click+1;

            $item->save();

//               var_dump($data);

            Yii::$app->params['breadcrumbs']=array();

            Yii::$app->params['breadcrumbs'][]=Html::tag('a',"Home",['href'=>Yii::$app->homeUrl]);//面包屑

            $cat=\backend\models\Category::find()->select(['id','title','pid','name'])->where(['id'=>$item->category_id2])->one();

            if($cat->pid!=0){

                $ParCat=\backend\models\Category::find()->select(['id','title','pid','name'])->where(['id'=>$cat->pid])->one();

                Yii::$app->params['breadcrumbs'][]='>'.Html::tag('a',$ParCat['title'],['href'=>'/'.$ParCat['name'].'/']);



            }

            Yii::$app->params['breadcrumbs'][]='>'.Html::tag('a',$cat['title'],['href'=>'/'.$cat['name'].'/']);

            $this->data['id']=Yii::$app->request->get('id');
            $this->data['detail']=$item;
            $goods_ids = CategoryImages::find()->where(['category_id'=>$item->category_id])->select('images_id')->asArray()->all();
            $goods_ids = array_column($goods_ids,'images_id');
            $product_list=Images::find()->where(['id'=>$goods_ids])->limit(3)->orderBy('click desc')->all();

            $industrialBettery_tree=ArrayHelper::CategoryList(54);
            Yii::$app->params['industrialBettery_tree']=$industrialBettery_tree;
            $specialBattery_tree=ArrayHelper::CategoryList(61);
            Yii::$app->params['specialBattery_tree']=$specialBattery_tree;
            Yii::$app->params['product_list']=$product_list;
            return $this->render('detail',['data'=>$this->data,'item'=>$item]);

        }



    }



    public function common(){
        parent::common();
        $url=Yii::$app->request->hostInfo.Yii::$app->request->url;

        $UrlAd=UrlAd::find()->where(['url'=>$url])->one();

        Yii::$app->params['UrlAd']=$UrlAd;

        self::get_product_list();

        $lanmu_list=Category::find()->where(['pid'=>$this->lanmu['pid']]);

        $lanmu_p=Category::find()->where(['id'=>$this->lanmu['pid']])->asArray()->one();

        $this->view->params['lanmu_p']=$lanmu_p;

        $this->view->params['lanmu_list']=$lanmu_list;

        $this->view->params['action']=$this->lanmu['name'];

        $this->view->params['atrr_kong']='';

        $this->view->params['atrr_list']='';
        $pageSize = 24;
        $productProvider= new \yii\data\ActiveDataProvider([
            'query' => $this->view->params['product_list'],
            'pagination'=>[
                'pageSize'=>$pageSize,
                'pageSizeParam' => false,
            ],
        ]);


        Yii::$app->params['productProvider']=$productProvider;
        $total=ceil($productProvider->getTotalCount()/$pageSize);
        $nowpage = isset($_GET['page']) ? $_GET['page'] : 1;
        $prepage = $nowpage == 1 ? 0 : $nowpage - 1;       //上页
        $nextpage = $nowpage > $total - 1 ? $total : $nowpage + 1;      //下页
        $lastpage = $total; //最后一页

        if ($nowpage>$lastpage){//页面数大于最大数的时候，报404
            throw new \yii\web\NotFoundHttpException('The requested page does not exist.');
        }
//       $d= $productProvider->getPagination()->getPageSize();
        if ($prepage>0){

            if (isset($_GET['list'])){

                Yii::$app->params['previous_page']=Yii::$app->request->hostInfo.'/'.Yii::$app->params['controllerName'].'/list-'.$_GET['list'].'-p'.$prepage.'.html';
            }else{
                Yii::$app->params['previous_page']=Yii::$app->request->hostInfo.'/'.Yii::$app->params['controllerName'].'/'.$prepage.'/';
            }


        }
        if ($nextpage<=$lastpage){

            if (isset($_GET['list'])){

                Yii::$app->params['next_page']=Yii::$app->request->hostInfo.'/'.Yii::$app->params['controllerName'].'/list-'.$_GET['list'].'-p'.$nextpage.'.html';
            }else{
                Yii::$app->params['next_page']=Yii::$app->request->hostInfo.'/'.Yii::$app->params['controllerName'].'/'.$nextpage.'/';
            }


        }

        if ($nowpage<=$lastpage){
            $url=Yii::$app->request->getUrl();
            $site=SitemapProduct::find()->where(['url'=>$url])->one();
            if(strpos($url,'?') == false){
                if (!isset($site)){
                    $site_product=new SitemapProduct();
                    $site_product->url=$url;
                    $site_product->save();
                }
            }
        }


    }



    public function get_product_list(){

//       echo ArrayHelper::isIn('1',[1,2]);
        $order=0;
        $choose=array();


        $cate=Category::find()->where(['id'=>$this->lanmu['id']])->one();

        $arrt=AttrImagesSelect::find()->where(['attr_value_id'=>Yii::$app->request->get('list')])->one();

        if (!empty(Yii::$app->request->get('list'))){
            $list= explode('-',Yii::$app->request->get('list'));

            if(strpos(end($list),'o')===false){

//                echo '不存在！';
            }else{
                $order=str_replace('o','',end($list));
                array_pop($list);
//                echo '存在！';
            }


            $array=array();
            foreach ($list as $key=>$value){
                $arrayItem=ArrayHelper::getColumn(AttrImagesSelect::find()->where(['attr_value_id'=>$value])->asArray()->all(),'images_id');//选择的属性对于的商品
                if ($key>=1){
                    $array=array_merge($array,$arrayItem);
                    $array = ArrayHelper::FetchRepeatMemberInArray ($array);
                }else{
                    $array=array_merge($array,$arrayItem);
                }
            }

            if (empty($array) && count($list)>0){

                throw new \yii\web\NotFoundHttpException('The requested page does not exist.');
                die;

            }
            if($order==1){
                $product_list=$cate->getImages($array)->select(['id','title','cover'])->orderBy('dianya DESC');
            }
            elseif($order==2){
                $product_list=$cate->getImages($array)->select(['id','title','cover'])->orderBy('dianya asc');
            }
            elseif($order==3){
                $product_list=$cate->getImages($array)->select(['id','title','cover'])->orderBy('rongliang DESC');
            }
            elseif($order==4){
                $product_list=$cate->getImages($array)->select(['id','title','cover'])->orderBy('rongliang asc');
            }
            elseif($order==5){
                $product_list=$cate->getImages($array)->select(['id','title','cover'])->orderBy('create_time DESC');
            }
            else{
                $product_list=$cate->getImages($array)->select(['id','title','cover'])->orderBy(['top'=>SORT_DESC,'create_time'=>SORT_DESC]);
            }




            $imagesArray=$cate->getAttrImages($array)->with('attrName','attrValueName')->all();

            //显示已选择的属性

//            1.显示的属性id，根据属性类型的sort排序



//            $choose =AttrValue::find()->where(['id'=>$list])->all();

//            根据属性名的权重进行排序

            $chooseOrderby=AttrValue::find()

                ->from(AttrValue::tableName(). ' A')

                ->select(['A.*'])

                ->leftJoin(Attr::tableName(). ' B','A.attr_id=B.id')

                ->where(['A.id'=>$list])

                ->orderBy('B.sort')

                ->all();

            $choose=$chooseOrderby;





        }else{

            $product_list=$cate->getImages()->select(['id','title','cover'])->where(['status'=>1])->orderBy(['top'=>SORT_DESC,'create_time'=>SORT_DESC]);

            $imagesArray=$cate->getAttrImages()->with('attrName','attrValueName')->all();

        }
        
        if (count($imagesArray)<=0){
            throw new \yii\web\NotFoundHttpException('The requested page does not exist.');
            die;
        }




        $chooseIdArray=array();

        foreach ($choose as $k=>$v){

//                $chooseArray=ArrayHelper::getValue($v,'id');

            $chooseIdArray[$k]=$v->id;

        }

        $chooseId=ArrayHelper::array2string($chooseIdArray,'-');
        $this->view->params['chooseIdArray'] =$chooseIdArray;

        $this->view->params['chooseId'] =$chooseId;

        $this->view->params['choose'] =$choose;

        $this->view->params['order'] =$order;



//        var_dump($cate);

        //处理这个属性标签

//        var_dump($cate->getAttrImages()->all());

        //显示所有属性

        $attr_list=array();

        $chushizhi='';

        $index=-1;

        //            选择的属性

        $chooseArray=array();

        foreach ($choose as $k=>$v){

//                $chooseArray=ArrayHelper::getValue($v,'id');

            $chooseArray[$k]=$v->attr->name;

        }



        foreach ($imagesArray as $value){

            if (ArrayHelper::isIn($value->attrName->name,$chooseArray)){

                continue;

            }

            if ($chushizhi!=$value->attrName){

                $chushizhi=$value->attrName;

                $index++;

                $attr_list[$index]['attr']=$value->attrName->name;

                $attr_list[$index]['sort']=$value->attrName->sort;

            }

            $valueArray=array();

            $valueArray['name']=$value->attrValueName->name;

            $valueArray['id']=$value->attrValueName->id;

            $valueArray['sort']=$value->attrValueName->sort;

            $attr_list[$index]['values'][]=$valueArray;

        }

        foreach ($attr_list as $key=>$value){

            $attr_list[$key]['values']=ArrayHelper::list_sort_by( $value['values'],'sort');

        }

        $attr_list=ArrayHelper::list_sort_by($attr_list,'sort');

//        var_dump($attr_list);



        //处理商品列表

        $p_list=Images::find()

            ->with([

                'category'=>function ($query) {

                    $query->andWhere(['id' =>$this->lanmu['id']]);

                },

                'attrValue'=>function ($query) {

                    $query->andWhere(['attr_id' =>1]);

                },

            ])

            ->select(['id','title','cover'])->all();

        ;

//        $p_list=Images::find()

//            ->leftJoin('yii2_category_images', '`yii2_category_images`.`images_id` = `yii2_images`.`id`')

//            ->where(['category.id' => 3])

//            ->with('category')//定义的关联属性名称为blogs

//            ->all();

//          foreach ($p_list as $key=>$value){

////              echo $key;

//          }



//        var_dump($choose);



        $this->view->params['product_list']=$product_list;



        $this->view->params['attr_list']=$attr_list;

//        var_dump($attr_list);

//        var_dump($cate->getAttr());



//        SEO优化

        if (!empty(Yii::$app->request->isGet)) {
            $choose_attrValue = '';
            foreach ($choose as $key => $value) {
                if ($key==0){
                    $choose_attrValue=$value->name . ' ';
                }else{
                    $choose_attrValue = $choose_attrValue . ' ' . $value->name . ' ';
                }
            }
            $choose_categoryValue = Yii::$app->params['lanmu']['title'];
            if (count($choose)>0){
                $title = 'Custom '.$choose_attrValue . $choose_categoryValue . ' manufacturer | Large Power' ;
                $keywords = 'Custom ' .$choose_attrValue . $choose_categoryValue .' Manufacturer,Large Power' ;
                $description = 'As China manufacturer of ' . $choose_attrValue . $choose_categoryValue . ' , Large Power has been focusing on custom rechargeable ' . $choose_categoryValue  . ' pack for 16 years.';
                $this->view->params['meta_title'] = $title;
                $this->view->params['keywords'] = $keywords;
                $this->view->params['description'] = $description;
            }
        }
        Yii::$app->params['choose_attrValue']=$choose_attrValue;

//        获取当前url

    }
}
